### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by Chen-jia621** [LukasHedegaard/continual-transformers#4]
hello! I have installed  "continual-inference“ but I got this error，  I think it may be because the version of "continual-inference“ is incorrect. Could you please tell me the correct installed version of "continual-inference“?
  
 from continual.module import CallMode
ImportError: cannot import name 'CallMode'

**Comment by LukasHedegaard** [comment]
Hi, thank you for reporting this. The CallMode enum was discontinued as of continual-inference v1.0.0, so you will need to install v0.17.1 for now. I have update the version requirement of this repository accordingly. Let me know if the issue persists.
